TablasDeConversion.exe:	TablasDeConversion.o Conversion.o
	gcc TablasDeConversion.o	Conversion.o	-o TablasDeConversion.exe
Conversion.o: Conversion.c
	gcc	-c	Conversion.c	-o Conversion.o
TablasDeConversion.o: TablasDeConversion.c
	gcc	-c TablasDeConversion.c	-o TablasDeConversion.o